# Generated by Django 3.2.7 on 2021-09-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210906_0928'),
        ('basket', '0002_auto_20210906_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.CreateModel(
            name='Basket_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='basket.basket_items'),
        ),
    ]
