# Generated by Django 3.2.7 on 2021-09-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20210906_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_item',
        ),
        migrations.AddField(
            model_name='basket_item',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='basket.basket'),
        ),
    ]
